# Amino Acid Decode Prep

This notebook documents steps taken to create a set of keys for converting amino acid one letter codes to a larger set of information to be used by the CNN. 

Data references:

Nelson, David L.; Cox, Michael M. (2000). Lehninger Principles of Biochemistry (3rd ed.). Worth Publishers. ISBN 978-1-57259-153-0.

Kyte J, Doolittle RF (May 1982). "A simple method for displaying the hydropathic character of a protein". Journal of Molecular Biology. 157 (1): 105â€“32. CiteSeerX 10.1.1.458.454. doi:10.1016/0022-2836(82)90515-0. PMID 7108955.

Meierhenrich, Uwe J. (2008). Amino acids and the asymmetry of life (1st ed.). Springer. ISBN 978-3-540-76885-2.

Biochemistry, Harpers (2015). Harpers Illustrated Biochemistry (30st ed.). Lange. ISBN 978-0-07-182534-4.

In [64]:
import pandas as pd
import numpy as np

In [70]:
data_r = pd.read_csv('AA_info.csv')
data_r.head()

,Name,One Letter,Three Letter,mass,PI,pka,pkb,side chain,hydrophobic,pka.1,polar,ph,small,tiny,aromatic or aliphatic,van der waal volume,Hydrophobicity
0,Alanine,A,Ala,89.09404,6.01,2.35,9.87,-CH3,Yes,30.00,No,NaN,Yes,Yes,Aliphatic,67,0.33
1,Arginine,R,Arg,174.20274,10.76,1.82,8.99,-(CH2)3NH-C(NH)NH2,No,12.30,Yes,strongly basic,No,No,-,148,1.00
2,Asparagine,N,Asn,132.11904,5.41,2.14,8.72,-CH2CONH2,No,30.00,Yes,NaN,Yes,No,-,96,0.43
3,Aspartic acid,D,Asp,133.10384,2.85,1.99,9.90,-CH2COOH,No,3.67,Yes,acidic,Yes,No,-,91,2.66
4,Cysteine,C,Cys,121.15404,5.05,1.92,10.70,-CH2SH,Yes,8.55,No,acidic,Yes,Yes,-,86,0.22

In [28]:
data_r.columns

Index(['Name', 'One Letter', 'Three Letter', 'mass', 'PI', 'pka', 'pkb',
       'side chain', 'hydrophobic', 'pka.1', 'polar', 'ph', 'small', 'tiny',
       'aromatic or aliphatic', 'van der waal volume', 'Hydrophobicity'],
      dtype='object')

In [71]:
data_r.index = data_r['One Letter']
data_r.drop(['O', 'U'], inplace=True)

Numeric columns taken as is and scaled with standard scaler. Note that for pka.1, some amino acids do not have reported vlues. They are given a value of 30, which is consistent with their side chains expected to have significantly higher pka's than the ones with reported values.

In [54]:
data = data_r[['mass', 'PI', 'pka', 'pkb','pka.1','van der waal volume', 'Hydrophobicity']]
data.index = data_r['One Letter']

In [55]:
data

,mass,PI,pka,pkb,pka.1,van der waal volume,Hydrophobicity
One Letter,,,,,,,
A,89.09404,6.01,2.35,9.87,30.00,67,0.33
R,174.20274,10.76,1.82,8.99,12.30,148,1.00
N,132.11904,5.41,2.14,8.72,30.00,96,0.43
D,133.10384,2.85,1.99,9.90,3.67,91,2.66
C,121.15404,5.05,1.92,10.70,8.55,86,0.22
Q,146.14594,5.65,2.17,9.13,30.00,114,0.19
E,147.13074,3.15,2.10,9.47,4.25,109,1.67
G,75.06714,6.06,2.35,9.78,30.00,48,1.14
H,155.15634,7.60,1.80,9.33,6.54,118,1.34
I,131.17464,6.05,2.32,9.76,30.00,124,-0.81
L,131.17464,6.01,2.33,9.74,30.00,124,-0.69
K,146.18934,9.60,2.16,9.06,10.40,135,1.81
M,149.20784,5.74,2.13,9.28,30.00,124,-0.44
F,165.19184,5.49,2.20,9.31,30.00,135,-0.58
P,115.13194,6.30,1.95,10.64,30.00,90,-0.31
S,105.09344,5.68,2.19,9.21,30.00,73,0.33
T,119.12034,5.60,2.09,9.10,30.00,93,0.11
W,204.22844,5.89,2.46,9.41,30.00,163,-0.24
Y,181.19124,5.64,2.20,9.21,9.84,141,0.23
V,117.14784,6.00,2.39,9.74,30.00,105,-0.53

In [30]:
from sklearn.preprocessing import StandardScaler

In [56]:
ss = StandardScaler()
data = pd.DataFrame(ss.fit_transform(data), columns=data.columns, index=data.index)

In [40]:
data

,mass,PI,pka,pkb,pka.1,van der waal volume,Hydrophobicity
One Letter,,,,,,,
A,-1.589200,-0.009948,1.085750,0.709184,0.723605,-1.490636,-0.068747
R,1.239969,2.769560,-1.835303,-1.061261,-0.934901,1.370537,0.662374
N,-0.158970,-0.361043,-0.071648,-1.604466,0.723605,-0.466265,0.040375
D,-0.126234,-1.859052,-0.898361,0.769540,-1.743540,-0.642881,2.473808
C,-0.523467,-0.571701,-1.284161,2.379036,-1.286279,-0.819496,-0.188782
Q,0.307310,-0.220605,0.093694,-0.779600,0.723605,0.169551,-0.221519
E,0.340046,-1.683504,-0.292105,-0.095564,-1.689193,-0.007065,1.393495
G,-2.055480,0.019310,1.085750,0.528116,0.723605,-2.161775,0.815145
H,0.606832,0.920456,-1.945531,-0.377226,-1.474618,0.310843,1.033390
I,-0.190364,0.013459,0.920407,0.487878,0.723605,0.522782,-1.312744
L,-0.190364,-0.009948,0.975521,0.447641,0.723605,0.522782,-1.181797
K,0.308753,2.090775,0.038580,-0.920430,-1.112932,0.911337,1.546266
M,0.409093,-0.167941,-0.126763,-0.477819,0.723605,0.522782,-0.908991
F,0.940431,-0.314231,0.259037,-0.417463,0.723605,0.911337,-1.061762
P,-0.723653,0.159749,-1.118818,2.258324,0.723605,-0.678204,-0.767131
S,-1.057351,-0.203050,0.203923,-0.618650,0.723605,-1.278697,-0.068747
T,-0.591071,-0.249863,-0.347219,-0.839956,0.723605,-0.572235,-0.308817
W,2.238079,-0.080167,1.692006,-0.216276,0.723605,1.900384,-0.690746
Y,1.472280,-0.226457,0.259037,-0.618650,-1.165405,1.123275,-0.177870
V,-0.656640,-0.015799,1.306206,0.447641,0.723605,-0.148357,-1.007201

Boolean type columns are converted to 1,0 columns

In [57]:
# Hydrophobic is simple yes or no
for col in ['hydrophobic', 'polar']:
    data[col] = pd.get_dummies(data_r[col])['Yes']

In [59]:
all(data['hydrophobic'] != data['polar'])

True

In [60]:
# dropping polar as it is an inverse of hydrophobic
data.drop('polar', axis=1, inplace=True)

In [61]:
# Aromatic/Aliphatic are each yes or no, '-' is a 0 for both
data = pd.concat((data, pd.get_dummies(data_r['aromatic or aliphatic'])[['Aliphatic', 'Aromatic']]), axis=1)

In [62]:
data

,mass,PI,pka,pkb,pka.1,van der waal volume,Hydrophobicity,hydrophobic,Aliphatic,Aromatic
One Letter,,,,,,,,,,
A,-1.589200,-0.009948,1.085750,0.709184,0.723605,-1.490636,-0.068747,1,1,0
R,1.239969,2.769560,-1.835303,-1.061261,-0.934901,1.370537,0.662374,0,0,0
N,-0.158970,-0.361043,-0.071648,-1.604466,0.723605,-0.466265,0.040375,0,0,0
D,-0.126234,-1.859052,-0.898361,0.769540,-1.743540,-0.642881,2.473808,0,0,0
C,-0.523467,-0.571701,-1.284161,2.379036,-1.286279,-0.819496,-0.188782,1,0,0
Q,0.307310,-0.220605,0.093694,-0.779600,0.723605,0.169551,-0.221519,0,0,0
E,0.340046,-1.683504,-0.292105,-0.095564,-1.689193,-0.007065,1.393495,0,0,0
G,-2.055480,0.019310,1.085750,0.528116,0.723605,-2.161775,0.815145,1,0,0
H,0.606832,0.920456,-1.945531,-0.377226,-1.474618,0.310843,1.033390,0,0,1
I,-0.190364,0.013459,0.920407,0.487878,0.723605,0.522782,-1.312744,1,1,0
L,-0.190364,-0.009948,0.975521,0.447641,0.723605,0.522782,-1.181797,1,1,0
K,0.308753,2.090775,0.038580,-0.920430,-1.112932,0.911337,1.546266,0,0,0
M,0.409093,-0.167941,-0.126763,-0.477819,0.723605,0.522782,-0.908991,1,1,0
F,0.940431,-0.314231,0.259037,-0.417463,0.723605,0.911337,-1.061762,1,0,1
P,-0.723653,0.159749,-1.118818,2.258324,0.723605,-0.678204,-0.767131,1,0,0
S,-1.057351,-0.203050,0.203923,-0.618650,0.723605,-1.278697,-0.068747,0,0,0
T,-0.591071,-0.249863,-0.347219,-0.839956,0.723605,-0.572235,-0.308817,0,0,0
W,2.238079,-0.080167,1.692006,-0.216276,0.723605,1.900384,-0.690746,1,0,1
Y,1.472280,-0.226457,0.259037,-0.618650,-1.165405,1.123275,-0.177870,0,0,1
V,-0.656640,-0.015799,1.306206,0.447641,0.723605,-0.148357,-1.007201,1,1,0

The ph column can be converted to an ordinal as 'basic' and 'acidic' represent two ends of a scale.

In [76]:
ordinal = []
for i in data_r['ph']:
    if i == 'acidic':
        ordinal.append(-2)
    elif i == 'weak acidic':
        ordinal.append(-1)
    elif i == 'weak basic':
        ordinal.append(1)
    elif i == 'basic':
        ordinal.append(2)
    elif i == 'strongly basic':
        ordinal.append(3)
    else:
        ordinal.append(0)
data['ph'] = ordinal

In [77]:
pd.concat((data['ph'], data_r['ph']), axis=1)

           ph              ph
One Letter
A           0             NaN
R           3  strongly basic
N           0             NaN
D          -2          acidic
C          -2          acidic
Q           0             NaN
E          -2          acidic
G           0             NaN
H           1      weak basic
I           0             NaN
L           0             NaN
K           2           basic
M           0             NaN
F           0             NaN
P           0             NaN
S           0             NaN
T           0             NaN
W           0             NaN
Y          -1     weak acidic
V           0             NaN

Finally, the amino acids contain much more information not captured in the above columns. Their one letter codes are encoded in dummy variables for the CNN to have the opportunity to 'learn' more information from these.

In [89]:
letters = pd.DataFrame(data=pd.get_dummies(data_r.index))
letters.index = data_r.index
letters

            A  C  D  E  F  G  H  I  K  L  M  N  P  Q  R  S  T  V  W  Y
One Letter
A           1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
R           0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0
N           0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0
D           0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
C           0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
Q           0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0
E           0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
G           0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0
H           0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0
I           0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0
L           0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0
K           0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0
M           0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0  0  0
F           0  0  0  0  1  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0
P           0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0  0  0  0
S           0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0  0
T           0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0  0
W           0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0
Y           0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1
V           0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  0  1  0  0

In [93]:
for c in letters.columns:
    if letters[c][letters[c] == 1].name != c:
        print(c)